# Generated by Django 5.0.4 on 2025-02-17 05:14

import django.db.models.deletion
import ep05.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField(default=functools.partial(ep05.models.generate_int, *(8,), **{}), unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sku', models.IntegerField(default=functools.partial(ep05.models.generate_int, *(16,), **{}), unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=functools.partial(ep05.models.generate_int, *(5,), **{}), unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('barista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barista', to='ep05.barista')),
                ('items', models.ManyToManyField(related_name='orders', to='ep05.item')),
            ],
        ),
    ]
